version: "3"
services:
    elasticsearch:
        image: my-elasticsearch
        deploy:
            resources:
                mem_limit: 2048m
        ports:
            - "9200:9200"
        networks:
            - webnet
    logstash:
        image: my-logstash
        ports:
            - "9600:9600"
        networks:
            - webnet
        depends_on:
            - "elasticsearch"
    kibana:
        image: my-kibana
        ports:
            - "5601:5601"
        networks:
            - webnet
        depends_on:
            - "elasticsearch"
    visualizer:
        image: dockersamples/visualizer:stable
        ports:
            - "8080:8080"
        volumes:
            - "/var/run/docker.sock:/var/run/docker.sock"
        deploy:
            placement:
                constraints: [node.role == manager]
        networks:
            - webnet
networks:
    webnet:
